apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: staging
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: project/helm/techtrends
    repoURL: https://github.com/nguyenhaison99/nd064_course_1
    targetRevision: HEAD
  syncPolicy: {}